name: Metrics
on:
  # Aggiorna ogni 12 ore
  schedule: [{cron: "0 */12 * * *"}]
  # Permette di avviarlo manualmente
  workflow_dispatch:
  # Aggiorna ad ogni push sul main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Opzioni generali
          user: DanieleGotti  
          template: classic
          base: ""
          config_timezone: Europe/Rome

                    # Attività recente
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          # Abitudini e anzianità GitHub
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes

          # Calendario contributi
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Commit stats
          plugin_commit: yes

          # Achievement
          plugin_achievements: yes
          plugin_achievements_display: compact

          
          # Statistiche Linguaggi
          plugin_languages: yes
          plugin_languages_ignored: html, css  
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          # Opzione per i repository privati
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
